site_name: Artanis Framework
site_description: A lightweight, minimalist ASGI web framework for Python built with simplicity and performance in mind.
site_url: https://nordxai.github.io/Artanis
repo_url: https://github.com/nordxai/Artanis
repo_name: nordxai/Artanis

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_source: true
            show_root_heading: false
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_signature_annotations: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Your First App: getting-started/first-app.md
  - Tutorials:
    - Overview: tutorials/index.md
  - Examples:
    - Overview: examples/index.md
  - API Reference:
    - Core:
      - App: api/core/app.md
      - Router: api/core/router.md
      - Request: api/core/request.md
  - CLI:
    - Overview: cli/index.md
  - Contributing:
    - Documentation: contributing/documentation.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nordxai/Artanis
      name: Source Code
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/artanis/
      name: PyPI Package
  version:
    provider: mike
    default: stable

copyright: Copyright &copy; 2024 Artanis Framework
