name: Code Quality

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
        echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH

    - name: Install package and dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Ruff linting
      run: |
        source venv/bin/activate
        ruff check --output-format=github .

    - name: Run Ruff formatting check
      run: |
        source venv/bin/activate
        ruff format --check .

    - name: Run MyPy type checking
      run: |
        source venv/bin/activate
        mypy --package artanis --strict --ignore-missing-imports

    - name: Check if code is properly formatted
      run: |
        source venv/bin/activate
        echo "✅ All code quality checks passed"
